Repository Game-as-a-Service/Game-Lobby-Web, pull requests merged in 2023-06, with the labels that each got.

#108 doc: added badge storybook
  shared/components/Badge/Badge.stories.tsx
  shared/components/Badge/Badge.tsx
Labels: documentation, sprint 1

#122 feat: cover
  shared/components/Cover/Cover.stories.tsx
  shared/components/Cover/cover.test.tsx
  shared/components/Cover/index.tsx
Labels: sprint 1, feature, refactor

#127 feat: rooms
  components/rooms/RoomCard.tsx
  components/rooms/RoomsList.tsx
  containers/room/RoomListView.tsx
  mocks/room.ts
  next.config.js
  package.json
  pages/api/mock/rooms.ts
  pages/index.tsx
  pages/rooms.tsx
  public/images/game-avatar.jpg
  public/images/padlock.svg
  requests/rooms/index.ts
  styles/global.css
  yarn.lock
Labels: sprint 2, sprint 3, feature

#132 feature/breadcrumb
  .gitignore
  components/shared/Breadcrumb/Breadcrumb.tsx
  components/shared/Breadcrumb/BreadcrumbItem.tsx
  components/shared/Breadcrumb/breadcrumb.stories.tsx
  components/shared/Breadcrumb/breadcrumb.test.tsx
  components/shared/Breadcrumb/breadcrumbItem.test.tsx
  components/shared/Breadcrumb/index.tsx
Labels: documentation, sprint 1, sprint 3, feature

#101 Feature/create room
  components/lobby/CreateRoomModal/CreateRoomModal.tsx
  components/lobby/CreateRoomModal/GameListModal/GameList/CategoryTitle.tsx
  components/lobby/CreateRoomModal/GameListModal/GameList/GameItem.tsx
  components/lobby/CreateRoomModal/GameListModal/GameList/index.tsx
  components/lobby/CreateRoomModal/GameListModal/GameListModal.tsx
  components/lobby/CreateRoomModal/GameListModal/gameListModal.module.css
  components/lobby/CreateRoomModal/GameListModal/index.tsx
  components/lobby/CreateRoomModal/createRoomModall.module.css
  components/lobby/CreateRoomModal/index.tsx
  components/rooms/RoomCard.tsx
  components/rooms/UserCard/UserCard.test.tsx
  components/rooms/UserCard/UserCard.tsx
  components/shared/Cover/Cover.stories.tsx
  components/shared/Cover/cover.test.tsx
  components/shared/Cover/index.tsx
  components/shared/Input/Input.tsx
  components/shared/Input/input.test.tsx
  containers/provider/AuthProvider.tsx
  hooks/usePagination.ts
  hooks/useRoom.ts
  lib/env.ts
  mocks/games.ts
  mocks/room.ts
  mocks/rooms.ts
  pages/api/internal/[...slug].tsx
  pages/api/mock/games.ts
  pages/api/mock/rooms.ts
  pages/api/mock/rooms/[roomId].ts
  pages/index.tsx
  pages/rooms/[roomId]/index.tsx
  requests/games/index.ts
  requests/rooms/index.ts
  yarn.lock
Labels: sprint 2, feature

#126 feat: userinfo with editing
  components/lobby/UserInfoModal.tsx
  pages/api/mock/users/me.ts
  requests/users/index.ts
Labels: sprint 3, feature

#136 fix: some password input issues in create room
  components/lobby/CreateRoomModal/CreateRoomModal.tsx
  components/lobby/CreateRoomModal/GameListModal/GameList/GameItem.tsx
  requests/rooms/index.ts
Labels: bug

#137 refactor(cicd): containerize build-and-deploy
  .github/workflows/build-and-deploy.yaml
Labels: sprint 3, Infrastructure

#125 feat: knip scan workflow
  .github/workflows/ci.yaml
  .gitignore
  .knip.json
  package.json
  scripts/knipScanReporter.js
  yarn.lock
Labels: Infrastructure

#147 fix: login button to a element
  .env.development
  .env.example
  .env.production
  lib/env.ts
  pages/auth/token/[token].tsx
  pages/login.tsx
Labels: sprint 3, feature

#144 refactor: extract Room page components
  components/rooms/RoomBreadcrumb.tsx
  components/rooms/RoomButtonGroup.tsx
  components/rooms/RoomUserCardList/RoomUserCardList.tsx
  components/rooms/RoomUserCardList/UserCard/UserCard.test.tsx
  components/rooms/RoomUserCardList/UserCard/UserCard.tsx
  components/rooms/RoomUserCardList/index.ts
  mocks/room.ts
  pages/rooms/[roomId]/index.tsx
Labels: sprint 3, refactor

#139 feat/global 401 error handling
  components/util/api-history/ApiHistoryItem.tsx
  components/util/api-history/ApiHistoryList.tsx
  containers/provider/ApiHistoryProvider.tsx
  contexts/ApiHistoryContext.tsx
  hooks/context/useApiHistory.ts
  hooks/useRequest.ts
  lib/env.ts
  pages/_app.tsx
  public/images/check.svg
  public/images/error.svg
  public/images/pending.svg
  requests/request.ts
Labels: sprint 3, feature

#152 fix: resolve issue with multi-path icon display
  components/shared/Icon/Icon.tsx
  components/shared/Icon/group/arrow-right.ts
  components/shared/Icon/group/target.ts
  components/shared/Icon/types/types.ts
Labels: bug

#130 Feature/toast
  components/shared/Toast/CtxToastQueue.tsx
  components/shared/Toast/Toast.stories.tsx
  components/shared/Toast/Toast.test.tsx
  components/shared/Toast/Toast.tsx
  components/shared/Toast/ToastQueueContext.tsx
  components/shared/Toast/index.tsx
  components/shared/Toast/toastStoryArgTypes.ts
  components/shared/Toast/useToast.stories.tsx
  components/shared/Toast/useToast.tsx
  pages/_app.tsx
Labels: sprint 3, feature

#128 feat: 💄 add login layout
  components/shared/Icon/group/discord.ts
  components/shared/Icon/group/github.ts
  components/shared/Icon/group/google.ts
  components/shared/Icon/group/linkedin.ts
  components/shared/Icon/group/logo.ts
  pages/login.tsx
  public/images/login_bg.png
Labels: sprint 3, feature

#131 :white_check_mark: feat: layout
  components/lobby/UserInfoModal.tsx
  components/rooms/RoomCard.tsx
  components/rooms/RoomsList.tsx
  components/shared/Chat/ChatContent.tsx
  components/shared/Chat/ChatMessage.tsx
  components/shared/Chat/index.tsx
  components/shared/Cover/index.tsx
  components/shared/Footer.tsx
  components/shared/Header.tsx
  components/shared/Icon/group/home.tsx
  components/shared/Icon/group/news.tsx
  components/shared/Icon/group/rooms.tsx
  components/shared/Sidebar.tsx
  components/shared/Tabs/Tabs.tsx
  containers/layout/AppLayout.tsx
  containers/room/RoomListView.tsx
  hooks/usePagination.ts
  pages/_document.tsx
  pages/index.tsx
  pages/rooms.tsx
  public/images/icon_help.svg
  public/images/icon_message.svg
  public/images/icon_profile.svg
  public/images/icon_remind.svg
  public/images/logo.svg
  styles/global.css
  tailwind.config.js
Labels: sprint 3, feature, reviewing

#138 feat: chatroom in room page via websocket
  components/lobby/CreateRoomModal/GameListModal/GameListModal.tsx
  components/lobby/CreateRoomModal/GameListModal/gameListModal.module.css
  components/rooms/RoomChatroom/ChatMessage.test.tsx
  components/rooms/RoomChatroom/ChatMessage.tsx
  components/rooms/RoomChatroom/RoomChatroom.test.tsx
  components/rooms/RoomChatroom/RoomChatroom.tsx
  components/rooms/RoomChatroom/index.ts
  containers/provider/ChatroomProvider.tsx
  contexts/ChatroomContext.tsx
  hooks/context/useChatroom.ts
  package.json
  pages/_app.tsx
  pages/api/mock/socket.ts
  pages/rooms/[roomId]/index.tsx
  styles/global.css
  yarn.lock
Labels: sprint 3, feature

#153 feat: password field component
  components/lobby/CreateRoomModal/CreateRoomModal.tsx
  components/shared/PasswordField/PasswordField.stories.tsx
  components/shared/PasswordField/PasswordField.test.tsx
  components/shared/PasswordField/PasswordField.tsx
  components/shared/PasswordField/index.ts
Labels: sprint 3, feature, reviewing

#172 refactor: icon component
  .storybook/main.ts
  components/shared/Icon/Icon.tsx
  components/shared/Icon/group/discord.ts
  components/shared/Icon/group/github.ts
  components/shared/Icon/group/google.ts
  components/shared/Icon/group/linkedin.ts
  components/shared/Icon/group/logo.ts
  components/shared/Icon/icon.stories.tsx
  components/shared/Icon/icon.test.tsx
  components/shared/Icon/icons/index.ts
  components/shared/Icon/icons/svgs/check.svg
  components/shared/Icon/icons/svgs/discord.svg
  components/shared/Icon/icons/svgs/error.svg
  components/shared/Icon/icons/svgs/github.svg
  components/shared/Icon/icons/svgs/google.svg
  components/shared/Icon/icons/svgs/help.svg
  components/shared/Icon/icons/svgs/home.svg
  components/shared/Icon/icons/svgs/linkedin.svg
  components/shared/Icon/icons/svgs/logo.svg
  components/shared/Icon/icons/svgs/message.svg
  components/shared/Icon/icons/svgs/news.svg
  components/shared/Icon/icons/svgs/padlock.svg
  components/shared/Icon/icons/svgs/pending.svg
  components/shared/Icon/icons/svgs/profile.svg
  components/shared/Icon/icons/svgs/remind.svg
  components/shared/Icon/icons/svgs/rooms.svg
  components/shared/Icon/icons/svgs/target.svg
  lib/utils.ts
  pages/login.tsx
  yarn.lock
Labels: refactor, sprint 4

#164 feat: enter private room modal
  components/lobby/EnterPrivateRoomModal/EnterPrivateRoomModal.tsx
  components/lobby/EnterPrivateRoomModal/index.tsx
  components/shared/PasswordField/PasswordField.tsx
  containers/room/RoomListView.tsx
  lib/utils.ts
  mocks/room.ts
  pages/api/mock/rooms/[roomId]/index.ts
  pages/api/mock/rooms/[roomId]/players.ts
  requests/rooms/index.ts
Labels: feature, sprint 4

#181 feat: auto label based on PR title workflow
  .github/workflows/auto-label.yaml
Labels: feature

#182 ✅refactor: rooms
  components/shared/Tabs/Tab.tsx
  components/shared/Tabs/Tabs.stories.tsx
  components/shared/Tabs/Tabs.tsx
  containers/room/RoomListView.tsx
  pages/rooms.tsx
Labels: refactor

#160 feat: carousel
  components/shared/Carousel/Carousel.stories.tsx
  components/shared/Carousel/Carousel.test.tsx
  components/shared/Carousel/Carousel.tsx
  components/shared/Carousel/CarouselArrowButton.test.tsx
  components/shared/Carousel/CarouselArrowButton.tsx
  components/shared/Carousel/CarouselItem.test.tsx
  components/shared/Carousel/CarouselItem.tsx
  components/shared/Carousel/index.tsx
  components/shared/Carousel/mockData.ts
  components/shared/Icon/icons/index.ts
  components/shared/Icon/icons/svgs/arrow-next.svg
  components/shared/Icon/icons/svgs/arrow-prev.svg
  components/shared/Sidebar.tsx
  pages/index.tsx
Labels: sprint 3, feature, sprint 4

#177 feature/kick user and close room
  components/rooms/RoomButtonGroup.tsx
  components/rooms/RoomChatroom/RoomChatroom.tsx
  components/rooms/RoomUserCardList/RoomUserCardList.tsx
  components/rooms/RoomUserCardList/UserCard/UserCard.test.tsx
  components/rooms/RoomUserCardList/UserCard/UserCard.tsx
  components/shared/Icon/icons/index.ts
  components/shared/Icon/icons/svgs/kick_user.svg
  hooks/usePopup.tsx
  mocks/room.ts
  pages/api/mock/rooms/[roomId]/players/[userId].ts
  pages/rooms/[roomId]/index.tsx
  requests/rooms/index.ts
Labels: feature, sprint 4

#195 ✨ feat: use request add toast and fix bug
  components/lobby/EnterPrivateRoomModal/EnterPrivateRoomModal.tsx
  components/lobby/UserInfoModal.tsx
  components/rooms/RoomCard.tsx
  components/rooms/RoomsList.tsx
  hooks/useRequest.ts
  pages/login.tsx
  tailwind.config.js
Labels: bug, feature, sprint 4

#180 👁️ fix: rooms add layout
  components/rooms/RoomCard.tsx
  components/rooms/RoomsList.tsx
  components/shared/Chat/ChatMessage.tsx
  components/shared/Header.tsx
  components/util/api-history/ApiHistoryList.tsx
  containers/layout/AppLayout.tsx
  pages/rooms.tsx
  styles/global.css
Labels: bug, feature, reviewing, sprint 4

#161 feat: add lhci workflow
  .github/workflows/ci.yaml
  lighthouserc.js
  pages/_app.tsx
  scripts/lhciScanReporter.js
Labels: feature

#176 refactor: reduce docker image size by next output tracing
  .github/workflows/build-and-deploy.yaml
  docker/Dockerfile.production
  next.config.js
  package.json
  yarn.lock
Labels: refactor

#194 👁️ refactor: remove chatroom context
  components/rooms/RoomChatroom/RoomChatroom.tsx
  contexts/ChatroomContext.tsx
  hooks/context/useChatroom.ts
  hooks/useChatroom.ts
  pages/_app.tsx
  pages/api/mock/socket.ts
  pages/rooms/[roomId]/index.tsx
Labels: feature, refactor, reviewing, sprint 4

#200 refactor: toast context timer state & cb function
  components/shared/Toast/ToastQueueContext.tsx
Labels: refactor

#201 feat: remove gha cache after branch got deleted
  .github/workflows/ci.yaml
  .github/workflows/cleanup-cache-after-merge.yaml
Labels: feature

#205 👁️ feat: leave room
  pages/rooms/[roomId]/index.tsx
  requests/rooms/index.ts
Labels: feature, reviewing, sprint 4

#207 refactor: hide 'Ready' button when the user is the host
  components/rooms/RoomButtonGroup.tsx
Labels: refactor, spring5

#215 refactor: redefine CI workflow steps
  .github/workflows/ci.yaml
Labels: refactor

#159 feat: portal component
  components/shared/Modalow/Modalow.tsx
  components/shared/Modalow/Portal.tsx
  components/shared/Portal/Portal.tsx
  components/shared/Portal/index.tsx
  components/shared/Portal/portal.stories.tsx
  components/shared/Portal/protal.test.tsx
Labels: sprint 3, feature, reviewing
