Repository Game-as-a-Service/Game-Lobby-Web, pull requests merged in 2023-09, with the labels that each got.

#315 refactor: modified MessageType
  components/rooms/RoomChatroom/ChatMessage.test.tsx
  components/rooms/RoomChatroom/ChatMessage.tsx
  components/rooms/RoomChatroom/RoomChatroom.tsx
  components/rooms/RoomChatroom/index.ts
  containers/provider/ChatroomProvider.tsx
  pages/api/mock/socketio.ts
Labels: refactor, sprint 9

#319 refactor: add socket event of join room and leave room
  components/rooms/RoomChatroom/RoomChatroom.tsx
  containers/provider/ChatroomProvider.tsx
  contexts/SocketContext.tsx
Labels: refactor, spring 10

#320 fix: 🔧 unset image optimization
  next.config.js
Labels: bug, sprint 9

#321 feat: Socket.IO connects with the jwt token
  components/rooms/RoomChatroom/RoomChatroom.tsx
  containers/provider/SocketProvider.tsx
  contexts/SocketContext.tsx
  pages/api/mock/socketio.ts
Labels: feature

#324 🐛 fix production external images not displaying
  components/shared/Avatar/Avatar.tsx
Labels: bug, sprint 9
