Repository Game-as-a-Service/Game-Lobby-Web, pull requests merged in 2023-07, with the labels that each got.

#211 👁️ feat: ready room
  components/rooms/RoomButtonGroup.tsx
  pages/api/mock/rooms/[roomId]/players/[userId].ts
  pages/api/mock/rooms/[roomId]/players/index.ts
  pages/rooms/[roomId]/index.tsx
  requests/rooms/index.ts
Labels: feature, spring5

#216 refactor: integrated component with portal
  components/shared/Chat/index.tsx
  components/shared/Portal/Portal.tsx
  components/shared/Toast/CtxToastQueue.tsx
  components/shared/Toast/ToastQueueContext.tsx
  pages/_document.tsx
Labels: refactor, sprint 4

#212 fix: userinfomodal loading disable other actions
  components/lobby/UserInfoModal.tsx
Labels: bug, sprint 3

#218 👁️ fix: email read only in UserInfoModal
  components/lobby/UserInfoModal.tsx
Labels: bug, spring5

#199 feat: add whyDidYouRender debugging tool
  package.json
  pages/_app.tsx
  scripts/whyDidYouRender.ts
  yarn.lock
Labels: feature

#213 feat: ts-reset to add strict type casting
  package.json
  reset.d.ts
  yarn.lock
Labels: feature

#224 fix(api): get games
  components/lobby/CreateRoomModal/CreateRoomModal.tsx
  components/lobby/CreateRoomModal/GameListModal/GameList/GameItem.tsx
  mocks/games.ts
  requests/games/index.ts
Labels: bug, refactor, spring5

#204 Revert "👁️ refactor: remove chatroom context"
  components/rooms/RoomChatroom/RoomChatroom.tsx
  containers/provider/ChatroomProvider.tsx
  contexts/ChatroomContext.tsx
  hooks/context/useChatroom.ts
  pages/_app.tsx
  pages/api/mock/socket.ts
  pages/rooms/[roomId]/index.tsx
Labels: refactor

#219 ✨ feat: enter room
  components/lobby/EnterPrivateRoomModal/EnterPrivateRoomModal.tsx
  components/shared/PasswordField/PasswordField.tsx
  containers/room/RoomListView.tsx
  mocks/room.ts
  mocks/rooms.ts
  pages/api/mock/rooms/[roomId]/players/index.ts
  requests/rooms/index.ts
Labels: feature, sprint 4

#223 fix: reslove flashing-popup issue#220
  hooks/usePopup.tsx
Labels: bug

#210 refactor: remove duplicate exports, unused Modal and props-type
  components/lobby/CreateRoomModal/GameListModal/GameList/index.tsx
  components/lobby/UserInfoModal.tsx
  components/rooms/RoomBreadcrumb.tsx
  components/rooms/RoomButtonGroup.tsx
  components/rooms/RoomChatroom/RoomChatroom.tsx
  components/rooms/RoomUserCardList/RoomUserCardList.tsx
  components/rooms/RoomUserCardList/UserCard/UserCard.tsx
  components/rooms/RoomsList.tsx
  components/shared/Avatar/Avatar.tsx
  components/shared/Badge/Badge.tsx
  components/shared/Badge/index.ts
  components/shared/Button/Button.tsx
  components/shared/Button/index.tsx
  components/shared/Carousel/Carousel.tsx
  components/shared/Carousel/CarouselArrowButton.tsx
  components/shared/Carousel/CarouselItem.tsx
  components/shared/Cover/index.tsx
  components/shared/Icon/Icon.tsx
  components/shared/Input/Input.tsx
  components/shared/Input/index.tsx
  components/shared/Input/input.test.tsx
  components/shared/Modal/ModalManager/index.tsx
  components/shared/Modal/ModalManager/src/ModalManager.tsx
  components/shared/Modal/ModalManager/src/ModalManagerBase.tsx
  components/shared/Modal/ModalManager/src/ModalStore.tsx
  components/shared/Modal/ModalManager/src/typings.ts
  components/shared/Modal/ModalManager/src/utils.tsx
  components/shared/Modal/index.tsx
  components/shared/Modalow/Body.tsx
  components/shared/Modalow/Example.tsx
  components/shared/Modalow/Footer.tsx
  components/shared/Modalow/Header.tsx
  components/shared/Modalow/Mask.tsx
  components/shared/Modalow/Modalow.tsx
  components/shared/Modalow/index.tsx
  components/shared/Portal/Portal.tsx
  components/shared/SearchBar/SearchBar.tsx
  components/shared/SearchBar/index.tsx
  components/shared/SearchBar/searchBar.test.tsx
  components/shared/Tabs/Tab.tsx
  components/shared/Tabs/Tabs.tsx
  components/shared/Tag/Tag.tsx
  components/shared/Toast/CtxToastQueue.tsx
  components/shared/Toast/Toast.tsx
  components/shared/Toast/ToastQueueContext.tsx
  components/shared/Toast/constants.ts
  components/shared/Toast/useToast.stories.tsx
  components/shared/Toast/useToast.tsx
  containers/provider/ChatroomProvider.tsx
  hooks/useCookie.ts
  package.json
  pages/_app.tsx
  pages/api/mock/socket.ts
  requests/rooms/index.ts
  requests/users/index.ts
  yarn.lock
Labels: refactor, spring5

#225 refactor/mock room api responses
  pages/api/mock/rooms/[roomId]/index.ts
  pages/api/mock/rooms/[roomId]/players/[userId].ts
  pages/rooms/[roomId]/index.tsx
Labels: refactor

#232 fix: sidebar links
  components/shared/Sidebar.tsx
Labels: bug, sprint 4, spring5

#248 fix: #237 remove anything temporarily useless
  components/shared/Header.tsx
  components/shared/Sidebar.tsx
  containers/room/RoomListView.tsx
Labels: bug

#231 fix/private selected
  components/lobby/CreateRoomModal/CreateRoomModal.tsx
  components/shared/PasswordField/PasswordField.tsx
Labels: bug, reviewing

#250 feat: i18n
  configs/i18nConfigs.ts
  containers/room/RoomListView.tsx
  next-i18next.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/rooms.tsx
  public/locales/zh-tw/rooms.json
  yarn.lock
Labels: feature, reviewing, sprint6

#257 fix(i18n): add common json
  public/locales/zh-tw/common.json
Labels: bug

#258 :bug: fix(auth): tmp rm authentication
  containers/util/Startup.tsx
Labels: bug
