Repository Game-as-a-Service/Game-Lobby-Web, pull requests merged in 2023-05, with the labels that each got.

#36 feat: http-client
  configs/axios.ts
  package.json
  pages/_app.tsx
  pages/api/internal/[...slug].tsx
  requests/request.ts
  shared/containers/provider/AxiosProvider.tsx
  shared/contexts/AxiosContext.tsx
  shared/hooks/context/useAxios.ts
  shared/hooks/useRequest.ts
  yarn.lock
Labels: enhancement, sprint 2

#38 feat: layout
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/without-layout.tsx
  shared/components/Layout.tsx
  shared/components/layout.tsx
  shared/containers/layout/AppLayout.tsx
Labels: enhancement, sprint 2

#41 feat: button
  shared/components/Button/Button.tsx
  shared/components/Button/button.test.tsx
  shared/components/Button/index.tsx
Labels: enhancement, sprint 2

#42 feat: avatar
  shared/components/Avatar/Avatar.test.tsx
  shared/components/Avatar/Avatar.tsx
  shared/components/Avatar/index.tsx
Labels: enhancement, sprint 2

#53 feat: badge
  shared/components/Badge/Badge.tsx
  shared/components/Badge/badge.test.tsx
  shared/components/Badge/index.ts
Labels: sprint 2

#56 feat: 🎸 modal
  pages/_app.tsx
  pages/index.tsx
  shared/components/Modal/ModalManager/index.tsx
  shared/components/Modal/ModalManager/src/Modal.types.ts
  shared/components/Modal/ModalManager/src/ModalManager.tsx
  shared/components/Modal/ModalManager/src/ModalManagerBase.tsx
  shared/components/Modal/ModalManager/src/ModalStore.tsx
  shared/components/Modal/ModalManager/src/utils.tsx
  shared/components/Modal/example/ModalExample1.tsx
  shared/components/Modal/example/ModalExample2.tsx
  shared/components/Modal/example/ModalExample3.tsx
  shared/components/Modal/index.tsx
Labels: sprint 2

#52 feat: icon
  shared/components/Icon/Icon.tsx
  shared/components/Icon/group/arrow-right.ts
  shared/components/Icon/icon.test.tsx
  shared/components/Icon/index.tsx
  shared/components/Icon/types/types.ts
Labels: sprint 2

#51 feat: ✨ input
  shared/components/Input/Input.tsx
  shared/components/Input/index.tsx
  shared/components/Input/input.test.tsx
Labels: sprint 2

#43 feat: tabs
  shared/components/Tabs/Tab.test.tsx
  shared/components/Tabs/Tab.tsx
  shared/components/Tabs/Tabs.test.tsx
  shared/components/Tabs/Tabs.tsx
  shared/components/Tabs/index.tsx
Labels: sprint 2

#59 feat: ✨ search bar
  shared/components/SearchBar/SearchBar.tsx
  shared/components/SearchBar/index.tsx
  shared/components/SearchBar/searchBar.test.tsx
Labels: sprint 2

#63 fix: model
  pages/index.tsx
  shared/components/Modal/ModalManager/src/ModalManager.tsx
  shared/components/Modal/ModalManager/src/ModalManagerBase.tsx
  shared/components/Modal/ModalManager/src/ModalStore.tsx
  shared/components/Modal/ModalManager/src/typings.ts
  shared/components/Modal/example/ModalExample1.tsx
  shared/components/Modal/example/ModalExample2.tsx
  shared/components/Modal/example/ModalExample3.tsx
  shared/components/Modal/index.tsx
Labels: bug, sprint 3

#37 feat: tag
  .prettierrc
  cypress/tsconfig.json
  jest.config.mjs
  package.json
  shared/components/Avatar/Avatar.test.tsx
  shared/components/Badge/badge.test.tsx
  shared/components/Button/button.test.tsx
  shared/components/Icon/icon.test.tsx
  shared/components/Input/input.test.tsx
  shared/components/SearchBar/searchBar.test.tsx
  shared/components/Tabs/Tab.test.tsx
  shared/components/Tabs/Tabs.test.tsx
  shared/components/Tag/Tag.tsx
  shared/components/Tag/index.ts
  shared/components/Tag/tag.stories.tsx
  shared/components/Tag/tag.test.tsx
  tsconfig.json
  tsconfig.test.json
  yarn.lock
Labels: sprint 2

#69 refactor: modal
  shared/components/Modalow/Body.tsx
  shared/components/Modalow/Example.tsx
  shared/components/Modalow/Footer.tsx
  shared/components/Modalow/Header.tsx
  shared/components/Modalow/Icon.tsx
  shared/components/Modalow/Mask.tsx
  shared/components/Modalow/Modalow.stories.tsx
  shared/components/Modalow/Modalow.tsx
  shared/components/Modalow/Portal.tsx
  shared/components/Modalow/index.tsx
  shared/components/Modalow/modal.module.css
  shared/components/Modalow/modalow.test.tsx
Labels: refactor

#86 fix: Adjusted modal style
  shared/components/Modalow/Body.tsx
  shared/components/Modalow/Modalow.tsx
Labels: bug

#70 feat: production dockerfile optimization
  .dockerignore
  docker/Dockerfile.production
  next.config.js
Labels: sprint 3, refactor

#75 doc: 📝 add button story book
  shared/components/Button/Button.stories.ts
  shared/components/Button/Button.tsx
  shared/components/Button/button.stories.tsx
Labels: documentation, refactor

#96 chore: storybook unmet peer dependencies
  .github/workflows/build-and-deploy.yaml
  package.json
  yarn.lock
Labels: Infrastructure

#77 feat: create-nickname
  .eslintrc.json
  core/lobby/components/UserInfoModal.tsx
  pages/api/internal/[...slug].tsx
  pages/api/mock/users/me.ts
  pages/index.tsx
  requests/request.ts
  requests/users/index.ts
  styles/global.css
  tailwind.config.js
  yarn.lock
Labels: sprint 3, feature

#97 doc: add avatar storybook
  shared/components/Avatar/Avatar.stories.tsx
  shared/components/Avatar/Avatar.tsx
Labels: documentation, refactor

#81 doc: 📝 add input story book
  .storybook/preview.ts
  shared/components/Input/Input.tsx
  shared/components/Input/input.stories.tsx
  shared/components/Input/input.test.tsx
Labels: documentation, refactor

#83 doc: 📝 add search bar story book
  shared/components/SearchBar/SearchBar.tsx
  shared/components/SearchBar/searchBar.stories.tsx
  shared/components/SearchBar/searchBar.test.tsx
Labels: documentation, refactor

#121 feat: pagination hook & room api pagination demo
  mocks/room.ts
  pages/api/mock/rooms.ts
  pages/index.tsx
  requests/rooms/index.ts
  shared/components/Sidebar.tsx
  shared/containers/layout/AppLayout.tsx
  shared/hooks/usePagination.ts
Labels: sprint 3, feature

#109 feat: add next.js bundle analyzer
  next.config.js
  package.json
  yarn.lock
Labels: sprint 3, Infrastructure
