Repository Game-as-a-Service/Game-Lobby-Web, pull requests merged in 2023-08, with the labels that each got.

#247 feat: start game
  mocks/room.ts
  pages/api/mock/rooms/[roomId]/index.ts
  pages/rooms/[roomId]/index.tsx
  requests/rooms/index.ts
  yarn.lock
Labels: feature, reviewing, sprint6

#261 refactor: socket.io infra and decouple ws and chatroom
  .vscode/settings.json
  components/rooms/RoomChatroom/RoomChatroom.tsx
  containers/provider/ChatroomProvider.tsx
  containers/provider/SocketProvider.tsx
  containers/util/Startup.tsx
  contexts/ChatroomContext.tsx
  contexts/SocketContext.tsx
  hooks/context/useSocketCore.ts
  package.json
  pages/_app.tsx
  pages/api/mock/socket.ts
  pages/api/mock/socketio.ts
  yarn.lock
Labels: refactor

#262 fix: context lost after navigated
  containers/provider/AuthProvider.tsx
  containers/room/RoomListView.tsx
  hooks/useUser.ts
  pages/auth/login.tsx
  pages/auth/token/[token].tsx
  pages/login.tsx
  pages/rooms/[roomId]/index.tsx
Labels: bug

#246 feature/websocket history
  components/shared/Icon/icons/index.ts
  components/shared/Icon/icons/svgs/arrow-down.svg
  components/shared/Icon/icons/svgs/arrow-up.svg
  components/shared/Icon/icons/svgs/thunder.svg
  components/util/api-history/ApiHistoryList.tsx
  components/util/history/ApiHistoryItem.tsx
  components/util/history/HistoryList.tsx
  components/util/history/WsHistoryItem.tsx
  containers/provider/ApiHistoryProvider.tsx
  containers/provider/ChatroomProvider.tsx
  containers/provider/HistoryProvider.tsx
  containers/provider/SocketProvider.tsx
  contexts/ApiHistoryContext.tsx
  contexts/HistoryContext.tsx
  hooks/context/useApiHistory.ts
  hooks/context/useHistory.ts
  hooks/useRequest.ts
  package.json
  pages/_app.tsx
  pages/api/mock/socket.ts
  pages/api/mock/socketio.ts
  yarn.lock
Labels: feature, sprint6

#269 fix: LHCI Failure
  containers/provider/SocketProvider.tsx
Labels: bug

#268 fix: update Storybook packages to version 7.2.3
  package.json
  yarn.lock
Labels: bug

#278 revert: [RENOVATE-BOT] Update dependencies (non-major)"
  package.json
  yarn.lock
Labels: dependency upgrade

#265 fix: create public room no password
  components/lobby/CreateRoomModal/CreateRoomModal.tsx
  requests/rooms/index.ts
  yarn.lock
Labels: bug, reviewing, sprint6

#273 feat: implement room features via Socket.IO
  components/rooms/RoomBreadcrumb.tsx
  contexts/SocketContext.tsx
  hooks/usePopup.tsx
  hooks/useRoom.ts
  mocks/room.ts
  pages/api/mock/socketio.ts
  pages/rooms/[roomId]/index.tsx
  requests/rooms/index.ts
Labels: feature, reviewing, sprint6

#284 fix: #281-RoomListView render error
  hooks/usePagination.ts
  pages/api/mock/rooms.ts
  requests/rooms/index.ts
Labels: bug, sprint 9

#286 fix: socket couldn't disconnect during leaving or refreshing page
  components/rooms/RoomChatroom/RoomChatroom.tsx
  containers/provider/SocketProvider.tsx
  contexts/SocketContext.tsx
  pages/api/mock/socketio.ts
Labels: bug, sprint 9

#288 fix: modify DEFAULT_PAGE from 1 to 0 in usePagination hook
  hooks/usePagination.ts
Labels: bug, sprint 9

#292 fix i18n not working in production issue
  next-i18next.config.js
Labels: bug, sprint 9

#295 fix i18next configuration not taking effect
  docker/Dockerfile.production
Labels: bug, sprint 9

#297 🐛 fix i18n not working in production issue
  docker/Dockerfile.production
  next-i18next.config.js
Labels: bug, sprint 9

#299 🐛 fix i18n production not match json file
  next-i18next.config.js
Labels: bug

#293 feat: opening gameUrl with token via Iframe
  components/rooms/GameWindow.test.tsx
  components/rooms/GameWindow.tsx
  pages/api/mock/rooms.ts
  pages/api/mock/socketio.ts
  pages/rooms/[roomId]/index.tsx
Labels: feature, sprint 9

#289 feat: fast join room
  components/lobby/FastJoinButton.tsx
  pages/api/internal/[...slug].tsx
  pages/api/mock/games.ts
  pages/api/mock/rooms/fastJoin/index.tsx
  pages/index.tsx
  requests/rooms/index.ts
Labels: feature, sprint 6

#304 feat: fast join room
  components/lobby/FastJoinButton.tsx
  pages/api/internal/[...slug].tsx
  pages/api/mock/games.ts
  pages/api/mock/rooms/fastJoin/index.tsx
  pages/index.tsx
  requests/rooms/index.ts
Labels: feature, sprint 6

#302 fix: dependabot ci failure issue
  .github/dependabot.yml
  .github/workflows/auto-label.yaml
Labels: bug

#313 Revert "fix: dependabot ci failure issue"
  .github/dependabot.yml
  .github/workflows/auto-label.yaml
Labels: bug
