Repository Game-as-a-Service/Game-Lobby-Web, pull requests merged in 2024-07, with the labels that each got.

#391 fix: use useSearchParams for token retrieval instead use useRouter
  pages/auth/token/[token].tsx
Labels: bug

#392 refactor: layout style and button
  components/shared/Header.tsx
  components/shared/Sidebar.tsx
  containers/layout/AppLayout.tsx
  hooks/useRequest.ts
  pages/index.tsx
  tailwind.config.js
Labels: refactor

#400 feat: update search bar
  components/shared/SearchBar/SearchBar.tsx
  components/shared/SearchBar/searchBar.stories.tsx
  components/shared/SearchBar/searchBar.test.tsx
Labels: feature

#401 feature: update layout v2
  components/shared/Chat/v2/Chat.tsx
  components/shared/Chat/v2/ChatHeader.tsx
  components/shared/Header.tsx
  components/shared/SearchBar/SearchBar.tsx
  components/shared/Sidebar.tsx
  containers/layout/AppLayout.tsx
  pages/_document.tsx
  pages/index.tsx
  tailwind.config.js
Labels: feature, v2

#403 feat: try to read room info first before join room
  containers/room/RoomListView.tsx
Labels: feature
